# Generated by Django 3.2.6 on 2022-09-03 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_number', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Plan_It_Teknoy.users')),
                ('first_name', models.CharField(default='Not set', max_length=50)),
                ('middle_name', models.CharField(default='Not set', max_length=50)),
                ('last_name', models.CharField(default='Not set', max_length=50)),
                ('gender', models.CharField(default='Not set', max_length=20)),
                ('department', models.CharField(default='Not set', max_length=50)),
                ('program', models.CharField(default='Not set', max_length=50)),
                ('year_level', models.IntegerField(default='Not set')),
                ('contact_number', models.CharField(default='Not set', max_length=50)),
                ('home_address', models.CharField(default='Not set', max_length=100)),
                ('city_address', models.CharField(default='Not set', max_length=100)),
                ('permissions', models.CharField(default='Not set', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Plan_It_Teknoy.users')),
                ('first_name', models.CharField(default='Not set', max_length=50)),
                ('middle_name', models.CharField(default='Not set', max_length=50)),
                ('last_name', models.CharField(default='Not set', max_length=50)),
                ('gender', models.CharField(default='Not set', max_length=20)),
                ('department', models.CharField(default='Not set', max_length=50)),
                ('program', models.CharField(default='Not set', max_length=50)),
                ('contact_number', models.CharField(default='Not set', max_length=50)),
                ('home_address', models.CharField(default='Not set', max_length=100)),
                ('city_address', models.CharField(default='Not set', max_length=100)),
                ('permissions', models.CharField(default='Not set', max_length=100)),
            ],
        ),
    ]
