# Generated by Django 3.2.6 on 2022-09-13 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Plan_It_Teknoy', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('StudentID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Plan_It_Teknoy.users')),
            ],
        ),
    ]
