# Generated by Django 3.2.6 on 2022-09-13 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Plan_It_Teknoy', '0005_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='StudentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plan_It_Teknoy.users'),
        ),
    ]
