# Generated by Django 3.2.6 on 2022-09-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan_It_Teknoy', '0006_alter_event_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='StudentID',
            field=models.CharField(default='Not set', max_length=50),
        ),
    ]
