# Generated by Django 4.1 on 2022-10-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan_It_Teknoy', '0010_alter_students_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id_number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
