# Generated by Django 4.1 on 2022-11-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan_It_Teknoy', '0012_alter_students_year_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='students_temp_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='users',
            name='users_temp_id',
            field=models.IntegerField(default=1),
        ),
    ]
