# Generated by Django 3.2.6 on 2022-11-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan_It_Teknoy', '0012_alter_students_year_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('DocumentID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('filename', models.CharField(default='Not set', max_length=50)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
    ]
