# Generated by Django 3.2.6 on 2022-11-16 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plan_It_Teknoy', '0013_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='DocumentGen',
        ),
    ]
