# Generated by Django 4.1 on 2022-11-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan_It_Teknoy', '0014_alter_students_students_temp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='students_temp_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='users_temp_id',
            field=models.IntegerField(default=1),
        ),
    ]
