# Generated by Django 3.2.6 on 2022-11-29 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plan_It_Teknoy', '0014_rename_document_documentgen'),
        ('Plan_It_Teknoy', '0015_alter_students_students_temp_id_and_more'),
    ]

    operations = [
    ]
